openapi: 3.0.0
info:
  title: Charging Station API
  version: 1.0.0
servers:
  - url: http://localhost:5000/api
paths:
  /auth/register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name: { type: string }
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: User created
  /auth/login:
    post:
      summary: Login and get JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200':
          description: JWT token
  /chargers:
    get:
      summary: List all chargers
      security: [{ bearerAuth: [] }]
      responses:
        '200':
          description: Charger list
    post:
      summary: Create a charger
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              properties:
                name: { type: string }
                location_lat: { type: number }
                location_lng: { type: number }
                status: { type: string }
                power_output: { type: number }
                connector_type: { type: string }
      responses:
        '200':
          description: Charger created
  /chargers/{id}:
    put:
      summary: Update a charger
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name: { type: string }
                location_lat: { type: number }
                location_lng: { type: number }
                status: { type: string }
                power_output: { type: number }
                connector_type: { type: string }
      responses:
        '200':
          description: Charger updated
    delete:
      summary: Delete a charger
      security: [{ bearerAuth: [] }]
      parameters:
        - name: id
          in: path
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Deleted
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
